parameters:
    database_driver: pdo_mysql
    database_host: 146.255.96.172
    database_port: 3306
    database_name: racoonweb_appquarium
    database_user: raccoon23
    database_password: rysu3eqeq
    sender_name: "Appquarium"
    mailer_transport: gmail
    mailer_host: smtp.gmail.com
    mailer_port: 465
    mailer_user: appquarium.supp@gmail.com
    mailer_newsletter_subject: 'Appquarium Newsletter'
    mailer_password: pececito
    mailer_message_subject: 'Appquarium Team'
    locale: es
    secret: ThisTokenIsNotSoSecretChangeItecret: ThisTokenIsNotSoSecretChangeIt
