security:

        encoders:
            FOS\UserBundle\Model\UserInterface: sha512

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email

        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt|error)|css|images|js)/
                security: false
            main:
                pattern: ^/
                form_login:
                    csrf_provider: form.csrf_provider
                    provider: fos_userbundle
                    check_path: /login_check
                    login_path: /login
                    use_forward: false
                    #always_use_default_target_path: true
                    #default_target_path:            /aquarium/dashboard
                    success_handler: login.redirection.success.handler
                    target_path_parameter:          false
                    use_referer:                    false
                    remember_me: true
                remember_me:
                   key: %secret%
                   lifetime: 31536000
                   path: ~
                   domain: ~
                   always_remember_me: false
                logout:       true
                anonymous:    true

        access_control:

             - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
             - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
             - { path: ^/aquarium/, role: ROLE_USER, requires_channel: https }
             - { path: ^/uploadImage/, role: ROLE_USER, requires_channel: https }
             - { path: ^/deleteImage/, role: ROLE_USER, requires_channel: https }
             - { path: ^/param/, role: ROLE_USER, requires_channel: https }
             - { path: ^/inhabitant/, role: ROLE_USER, requires_channel: https }
             - { path: ^/postAquarium/, role: ROLE_USER, requires_channel: https }
             - { path: ^/admin/, role: ROLE_ADMIN, requires_channel: https }